name: MachoCall
description: "MachoCall"
publish_to: 'none'

version: 1.3.4+5

environment:
  sdk: '>=3.7.0 <4.0.0' 

dependencies:
  flutter:
    sdk: flutter
  just_audio:
  google_mobile_ads:

  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/image/

flutter_icons:
  ios: true
  image_path: "assets/image/download.jpg"
  remove_alpha_ios: true
  android: true
  adaptive_icon_background: "assets/image/download.jpg"
  adaptive_icon_foreground: "assets/image/download.jpg"
